"""Datos de emojis: índice de búsqueda por palabras clave y Recientes.

El picker original buscaba por subcadena dentro del propio emoji (comparar
"fuego" contra "🔥" nunca coincide). Este módulo provee:

* `search_emojis(query)` -> emojis que coinciden con palabras/tags en
  español e inglés, sin acentos, con fallback a coincidencia de caracteres.
* `add_recent(emoji)` / `load_recent()` -> últimos emojis usados, que se
  persisten en el mismo directorio de caché que emoji_renderer.
"""

import unicodedata
from pathlib import Path

_RECENT_FILE = Path.home() / ".cache" / "telegram-ai-emoji" / "recent.json"
_RECENT_MAX = 36


def normalize(text: str) -> str:
    """Quita acentos/puntos diacríticos y pasa a minúsculas."""
    return "".join(
        c for c in unicodedata.normalize("NFD", text.lower())
        if unicodedata.category(c) != "Mn"
    )


# Emoji -> palabras clave (es ya sin acentos). Cubre los usos más comunes.
EMOJI_INDEX: dict[str, tuple[str, ...]] = {
    "😀": ("sonrisa", "feliz", "contento", "happy", "grin"),
    "😄": ("sonrisa", "feliz", "risa", "happy", "laugh"),
    "😁": ("sonrisa", "ojos", "feliz", "radiant", "grin"),
    "😆": ("risa", "ojos", "carcajada", "laugh", "squint"),
    "😅": ("risa", "nervioso", "sudor", "sweat", "smile"),
    "🤣": ("risa", "llorar", "carcajada", "laugh", "rofl"),
    "😂": ("risa", "llorar", "carcajada", "joy", "laugh"),
    "🙂": ("sonrisa", "timido", "neutral", "slight", "smile"),
    "🙃": ("sonrisa", "boca abajo", "upside", "sarcasmo"),
    "😉": ("guino", "guiño", "wink", "coqueto"),
    "😊": ("sonrisa", "ojos", "feliz", "blush", "smile"),
    "😇": ("angel", "inocente", "halo", "smile", "innocent"),
    "🥰": ("amor", "enamorado", "corazon", "love", "smile"),
    "😍": ("amor", "ojos corazon", "enamorado", "love", "eyes"),
    "🤩": ("estrella", "maravillado", "asombrado", "star", "eyes"),
    "😘": ("beso", "corazon", "love", "kiss"),
    "😗": ("beso", "kiss", "smile"),
    "☺️": ("sonrisa", "calida", "relajado", "relieved", "smile"),
    "😚": ("beso", "ojos", "kiss", "eyes"),
    "😙": ("beso", "sonrisa", "kiss", "smile"),
    "🥲": ("sonrisa", "lagrima", "agridulce", "smile", "tear"),
    "😋": ("rico", "delicioso", "lengua", "yummy", "savouring"),
    "😛": ("lengua", "sacar lengua", "tongue"),
    "😜": ("lengua", "guino", "wink", "tongue"),
    "🤪": ("loco", "desequilibrado", "crazy", "goofy"),
    "😝": ("lengua", "ojos", "tongue", "squint"),
    "🤑": ("dinero", "boca", "billete", "rich", "money"),
    "🤗": ("abrazo", "manos", "hug", "smile"),
    "🤭": ("boca tapada", "secreto", "risilla", "hush", "hand"),
    "🤫": ("silencio", "callar", "shush", "quiet"),
    "🤔": ("pensar", "pensativo", "duda", "thinking", "thoughtful"),
    "🤐": ("callado", "boca cerrada", "silencio", "zipper", "mouth"),
    "🤨": ("ceja", "esceptico", "duda", "raising", "eyeroll"),
    "😐": ("neutral", "serio", "neutral", "straight"),
    "😑": ("neutral", "aburrido", "annoyed", "expressionless"),
    "😏": ("sonrisa", "socarron", "malicia", "smirk", "sly"),
    "😒": ("disgusto", "antipatia", "unamused", "side"),
    "🙄": ("ojos", "molesto", "roll", "eyeroll"),
    "😬": ("nervioso", "dientes", "mueca", "grimacing"),
    "😔": ("triste", "serio", "pensive", "sad"),
    "😪": ("sueno", "dormir", "tired", "sleepy"),
    "🤤": ("babeando", "saliva", "drool", "yummy"),
    "😴": ("dormir", "sueno", "zzz", "sleeping"),
    "😷": ("mascarilla", "enfermo", "doctor", "mask"),
    "🤒": ("enfermo", "termometro", "sick", "fever"),
    "🤕": ("vendaje", "herido", "injured", "bandage"),
    "🤢": ("nauseas", "asqueado", "sick", "nauseated"),
    "🤮": ("vomitar", "nauseas", "vomit"),
    "🤧": ("estornudo", "resfriado", "sneeze", "cold"),
    "🥵": ("calor", "sudor", "ardiente", "hot", "heat"),
    "🥶": ("frio", "congelado", "cold", "freezing"),
    "🥴": ("mareado", "borracho", "woozy"),
    "😵": ("mareado", "ido", "dizzy", "knocked"),
    "🤯": ("explosion", "cabeza", "alucinar", "mind", "exploding"),
    "🤠": ("vaquero", "sombrero", "cowboy", "hat"),
    "🥳": ("fiesta", "celebracion", "gorro", "party", "celebration"),
    "🥸": ("disimulado", "nariz", "disfraz", "disguise"),
    "😎": ("gafas", "genial", "sol", "cool", "sunglasses"),
    "🤓": ("nerd", "gafas", "empollon", "glasses", "nerd"),
    "🧐": ("monoculo", "investigar", "examinar", "monocle"),
    "😕": ("confuso", "desconcertado", "confused"),
    "😟": ("preocupado", "serio", "worried", "concerned"),
    "🙁": ("serio", "triste", "insatisfecho", "slightly", "frowning"),
    "☹️": ("serio", "triste", "frown"),
    "😮": ("asombrado", "boca abierta", "surprised", "open"),
    "😯": ("sorprendido", "callado", "hushed"),
    "😲": ("asombrado", "ojos", "astonished", "amazed"),
    "😳": ("sonrojado", "avergonzado", "flushed", "embarrassed"),
    "🥺": ("ojos", "suplica", "tierno", "pleading", "puppy"),
    "😦": ("serio", "boca abajo", "frowning", "open"),
    "😧": ("angustiado", "asustado", "anguished"),
    "😨": ("asustado", "miedo", "fearful"),
    "😰": ("sudor", "angustia", "ansioso", "anxious", "cold"),
    "😥": ("triste", "aliviado", "sudor", "disappointed", "relieved"),
    "😢": ("lagrima", "triste", "llorar", "cry", "tear"),
    "😭": ("llorar", "lagrimas", "gritar", "crying", "sobbing"),
    "😱": ("grito", "terror", "miedo", "scream", "horror"),
    "😖": ("frustrado", "confundido", "confounded"),
    "😣": ("persistente", "dolor", "persevering"),
    "😞": ("decepcionado", "triste", "disappointed"),
    "😓": ("sudor", "triste", "downcast", "sweat"),
    "😩": ("cansado", "agotado", "weary"),
    "😫": ("cansado", "frustrado", "tired"),
    "🥱": ("bostezo", "sueno", "yawn", "sleepy"),
    "😤": ("enojo", "frustrado", "triumph"),
    "😡": ("enojado", "rojo", "angry", "rage"),
    "😠": ("enojado", "enfadado", "angry"),
    "🤬": ("insulto", "simbolos", "enojo", "cursing"),
    "😈": ("diablo", "malvado", "sonrisa", "imp", "devil"),
    "👿": ("diablo", "malvado", "angry", "imp", "devil"),
    "💀": ("calavera", "muerte", "skull"),
    "☠️": ("calavera", "huesos", "muerte", "pirata", "skull", "crossbones"),
    "💩": ("caca", "popo", "poop", "pile"),
    "🤡": ("payaso", "clown"),
    "👻": ("fantasma", "halloween", "ghost"),
    "👽": ("alien", "extraterrestre", "alien"),
    "🤖": ("robot", "bot", "robot"),
    "👋": ("saludo", "hola", "adiós", "wave", "hello"),
    "🤚": ("mano", "alto", "stop", "raised"),
    "🖐️": ("mano", "saludo", "hand"),
    "✋": ("mano", "alto", "stop", "hand"),
    "🖖": ("vulcano", "saludo", "spock", "vulcan"),
    "👌": ("ok", "perfecto", "ok", "perfect"),
    "🤌": ("pizza", "italiano", "palm", "pinched"),
    "🤏": ("pequeño", "pinza", "pinching", "small"),
    "✌️": ("victoria", "paz", "paz", "victory", "two"),
    "🤞": ("cruzar dedos", "suerte", "crossed", "fingers"),
    "🤟": ("te quiero", "rock", "love", "sign"),
    "🤘": ("rock", "metal", "sign", "horns"),
    "🤙": ("llamame", "telefono", "call me", "sign"),
    "👈": ("izquierda", "apuntar", "point", "left"),
    "👉": ("derecha", "apuntar", "point", "right"),
    "👆": ("arriba", "apuntar", "point", "up"),
    "🖕": ("insulto", "dedo", "middle", "finger"),
    "👇": ("abajo", "apuntar", "point", "down"),
    "☝️": ("arriba", "dedo", "point", "up"),
    "👍": ("pulgar arriba", "me gusta", "like", "thumbsup", "ok"),
    "👎": ("pulgar abajo", "no me gusta", "dislike", "thumbsdown"),
    "👊": ("puño", "golpe", "fist", "oncoming"),
    "✊": ("puño", "fuerza", "fist", "raised"),
    "🤛": ("puño", "izquierda", "fist", "left"),
    "🤜": ("puño", "derecha", "fist", "right"),
    "👏": ("aplausos", "bravo", "clap", "applause"),
    "🙌": ("manos arriba", "victoria", "raise", "hands", "celebration"),
    "👐": ("manos abiertas", "open", "hands"),
    "🤲": ("manos", "recibir", "palms", "offer"),
    "🤝": ("apreton", "pacto", "acuerdo", "handshake"),
    "🙏": ("gracias", "orar", "pfavor", "pray", "thank"),
    "✍️": ("escribir", "mano", "writing"),
    "💅": ("unas", "glamour", "nail", "polish"),
    "🤳": ("selfie", "celular", "selfie"),
    "💪": ("musculo", "fuerza", "powerful", "muscle", "biceps"),
    "🐶": ("perro", "cachorro", "dog", "puppy"),
    "🐱": ("gato", "miau", "cat", "kitten"),
    "🐭": ("raton", "mouse", "rat"),
    "🐹": ("hamster", "hamster"),
    "🐰": ("conejo", "bunny", "rabbit"),
    "🦊": ("zorro", "fox"),
    "🐻": ("oso", "bear"),
    "🐼": ("panda", "panda"),
    "🐨": ("koala", "koala"),
    "🐯": ("tigre", "tiger"),
    "🦁": ("leon", "lion"),
    "🐮": ("vaca", "cow"),
    "🐷": ("cerdo", "pig"),
    "🐸": ("rana", "frog"),
    "🐵": ("mono", "cara", "monkey"),
    "🙈": ("mono", "ojos", "no ver", "see", "monkey"),
    "🙉": ("mono", "oidos", "no oir", "hear", "monkey"),
    "🙊": ("mono", "boca", "no hablar", "speak", "monkey"),
    "🐔": ("pollo", "gallina", "chicken"),
    "🐧": ("pinguino", "penguin"),
    "🐦": ("pajaro", "bird"),
    "🐤": ("pollito", "baby chick"),
    "🐣": ("pollito", "salir", "eclosion", "hatching"),
    "🐥": ("pollito", "frente", "front", "chick"),
    "🦆": ("pato", "duck"),
    "🦅": ("aguila", "eagle"),
    "🦉": ("buho", "sabiduria", "owl"),
    "🦇": ("murcielago", "bat"),
    "🐺": ("lobo", "wolf"),
    "🐗": ("jabali", "boar"),
    "🐴": ("caballo", "horse"),
    "🦄": ("unicornio", "unicorn"),
    "🐝": ("abeja", "miel", "bee", "honeybee"),
    "🦋": ("mariposa", "butterfly"),
    "🐌": ("caracol", "snail"),
    "🐞": ("mariquita", "ladybug", "lady"),
    "🐢": ("tortuga", "turtle"),
    "🐍": ("serpiente", "snake"),
    "🦖": ("dinosaurio", "t-rex", "tirerop", "dinosaur"),
    "🦕": ("dinosaurio", "sauropodo", "sauropod", "dinosaur"),
    "🐬": ("delfin", "dolphin"),
    "🐳": ("ballena", "whale"),
    "🐋": ("ballena", "whale"),
    "🐊": ("cocodrilo", "crocodile"),
    "🍎": ("manzana", "apple"),
    "🍐": ("pera", "pear"),
    "🍊": ("naranja", "mandarina", "orange", "tangerine"),
    "🍋": ("limon", "lemon"),
    "🍌": ("platano", "banana"),
    "🍉": ("sandia", "watermelon"),
    "🍇": ("uva", "grapes"),
    "🍓": ("fresa", "frutilla", "strawberry"),
    "🍒": ("cerezas", "cherries"),
    "🍑": ("durazno", "melon", "peach"),
    "🥭": ("mango", "mango"),
    "🍍": ("pina", "pineapple"),
    "🥥": ("coco", "coconut"),
    "🥝": ("kiwi", "kiwi"),
    "🍅": ("tomate", "tomato"),
    "🍆": ("berenjena", "eggplant"),
    "🥑": ("aguacate", "palta", "avocado"),
    "🥦": ("brocoli", "broccoli"),
    "🥬": ("espinaca", "verdura", "greens", "leafy"),
    "🥒": ("pepino", "cucumber"),
    "🌶️": ("chile", "picante", "hot", "pepper"),
    "🌽": ("maiz", "corn"),
    "🥕": ("zanahoria", "carrot"),
    "🥔": ("papa", "patata", "potato"),
    "🍠": ("camote", "batata", "sweet", "potato"),
    "🥐": ("cruziente", "mediasluna", "croissant"),
    "🥖": ("baguette", "pan", "bread"),
    "🍞": ("pan", "bread"),
    "🥨": ("pretzel", "pretzel"),
    "🥯": ("bagel", "bagel"),
    "🥞": ("panqueques", "hotcakes", "pancakes"),
    "🧇": ("waffle", "waffle"),
    "🥓": ("tocino", "bacon"),
    "🥩": ("carne", "corte", "steak", "meat"),
    "🍗": ("pierna", "pollo", "poultry", "leg"),
    "🍖": ("carne", "hueso", "meat", "bone"),
    "🌭": ("hotdog", "perrito", "hotdog"),
    "🍔": ("hamburguesa", "burger"),
    "🍟": ("papas fritas", "fries", "chips"),
    "🍕": ("pizza", "pizza"),
    "🥪": ("sandwich", "sandwich"),
    "🥙": ("kebab", "pita", "wrap"),
    "🌮": ("taco", "taco"),
    "🌯": ("burrito", "burrito"),
    "🥗": ("ensalada", "salad"),
    "🥘": ("paella", "sarten", "shallow", "pan"),
    "🍝": ("pasta", "espagueti", "spaghetti"),
    "🍜": ("fideos", "ramen", "noodles"),
    "🍲": ("estofado", "sopa", "stew", "pot"),
    "🍛": ("curry", "arroz", "curry", "rice"),
    "🍣": ("sushi", "sushi"),
    "🍱": ("bento", "bento", "lunch"),
    "🥟": ("empanada", "dumpling", "gyoza"),
    "🍤": ("camaron", "frito", "shrimp", "tempura"),
    "🍙": ("oni", "arroz", "rice", "ball"),
    "🍚": ("arroz", "cocido", "rice", "cooked"),
    "🍘": ("galleta", "arroz", "rice", "cracker"),
    "🍥": ("naruto", "kamaboko", "fish", "cake"),
    "🥠": ("galleta", "fortuna", "fortune", "cookie"),
    "🍢": ("oden", "oden"),
    "🍡": ("dango", "dango"),
    "🍧": ("granizado", "raspado", "shaved", "ice"),
    "🍨": ("helado", "soft", "ice", "cream"),
    "🍦": ("helado", "cono", "icecream"),
    "🥧": ("tarta", "pie"),
    "🧁": ("cupcake", "magdalena", "cupcake"),
    "🍰": ("pastel", "torta", "cake"),
    "🎂": ("cumpleaños", "pastel", "birthday", "cake"),
    "🍮": ("flan", "crema", "custard"),
    "🍭": ("piruleta", "caramelo", "lollipop"),
    "🍬": ("caramelo", "dulce", "candy"),
    "🍫": ("chocolate", "chocolate"),
    "🍿": ("palomitas", "popcorn"),
    "🍩": ("dona", "rosquilla", "doughnut"),
    "🍪": ("galleta", "cookie"),
    "☕": ("cafe", "cafe", "coffee"),
    "🍵": ("te", "verde", "tea", "matcha"),
    "🧃": ("jugo", "caja", "juice", "box"),
    "🥤": ("gaseosa", "soda", "refresco", "cup", "straw"),
    "🧋": ("boba", "te", "bubble", "tea"),
    "🍺": ("cerveza", "beer"),
    "🍻": ("cervezas", "brindis", "beers", "toast"),
    "🥂": ("brindis", "copas", "champagne", "toast"),
    "🍷": ("vino", "wine"),
    "🥃": ("whisky", "traguito", "tumbler", "whiskey"),
    "🍸": ("coctel", "martini", "cocktail"),
    "🍹": ("tropical", "coctel", "tropical", "drink"),
    "🍾": ("champagne", "brindis", "bottle", "pop"),
    "🧊": ("hielo", "ice"),
    "⚽": ("futbol", "balon", "soccer", "football"),
    "🏀": ("baloncesto", "basquet", "basketball"),
    "🏈": ("futbol americano", "football", "american"),
    "⚾": ("beisbol", "baseball"),
    "🥎": ("softbol", "softball"),
    "🎾": ("tenis", "pelota", "tennis"),
    "🏐": ("voley", "volleyball"),
    "🏉": ("rugby", "rugby"),
    "🎱": ("billar", "ocho", "pool", "8ball"),
    "🏓": ("ping pong", "tenis de mesa", "ping", "table"),
    "🏸": ("badminton", "badminton"),
    "🏑": ("hockey", "palo", "field", "hockey"),
    "🏒": ("hockey", "hielo", "ice", "hockey"),
    "🥍": ("lacrosse", "lacrosse"),
    "🏏": ("cricket", "cricket"),
    "🥅": ("porteria", "goal", "net"),
    "⛳": ("golf", "bandera", "golf", "flag"),
    "🏹": ("arco", "flecha", "bow", "arrow"),
    "🎣": ("pesca", "caña", "fishing", "pole"),
    "🥊": ("boxeo", "guantes", "boxing", "glove"),
    "🥋": ("karate", "artes marciales", "martial", "arts"),
    "🎽": ("carrera", "camiseta", "running", "shirt"),
    "🛹": ("skate", "patineta", "skateboard"),
    "🛼": ("patines", "roller", "skate"),
    "⛸️": ("patinaje", "ice", "skate"),
    "🥌": ("curling", "piedra", "curling"),
    "🎿": ("esqui", "ski"),
    "🏂": ("snow", "esqui", "snowboarder"),
    "🏋️": ("pesas", "gimnasio", "levantamiento", "weight"),
    "🤼": ("lucha", "wrestling"),
    "🤸": ("gimnasia", "cartwheel"),
    "⛹️": ("balon", "pelota", "ball", "person"),
    "🤺": ("esgrima", "espada", "fencing"),
    "🤾": ("balonmano", "handball"),
    "🏌️": ("golf", "golpe", "golfing"),
    "🧘": ("meditacion", "yoga", "lotus", "person"),
    "🏄": ("surf", "surfing"),
    "🏊": ("natacion", "nadar", "swimming"),
    "🤽": ("waterpolo", "polo", "water"),
    "🚣": ("remo", "bote", "rowing", "boat"),
    "🧗": ("escalada", "roca", "climbing"),
    "🚵": ("ciclismo", "montaña", "bicyclist", "mountain"),
    "🚴": ("ciclismo", "bici", "bicicleta", "bicyclist"),
    "🏆": ("trofeo", "ganador", "campeon", "trophy"),
    "🥇": ("oro", "medalla", "primero", "gold", "first"),
    "🥈": ("plata", "medalla", "segundo", "silver", "second"),
    "🥉": ("bronce", "medalla", "tercero", "bronze", "third"),
    "🏅": ("medalla", "deporte", "medal", "sport"),
    "🎖️": ("medalla", "militar", "military", "medal"),
    "⌚": ("reloj", "smartwatch", "watch"),
    "📱": ("movil", "telefono", "smartphone", "phone"),
    "💻": ("computadora", "laptop", "ordenador", "computer", "laptop"),
    "⌨️": ("teclado", "keyboard"),
    "🖥️": ("monitor", "pantalla", "desktop", "computer"),
    "🖨️": ("impresora", "printer"),
    "🖱️": ("mouse", "raton", "computer"),
    "🕹️": ("joystick", "mando", "videojuego", "joystick"),
    "💽": ("disco", "minidisc", "computer"),
    "💾": ("disquete", "guardar", "floppy"),
    "💿": ("cd", "disco", "optical"),
    "📷": ("camara", "foto", "camera"),
    "📸": ("camara", "flash", "camera", "flash"),
    "📹": ("camara video", "video", "video", "camera"),
    "🎥": ("camara", "cine", "video", "movie", "camera"),
    "📞": ("telefono", "fijo", "receiver"),
    "☎️": ("telefono", "fijo", "telephone"),
    "📺": ("television", "tv", "television"),
    "📻": ("radio", "radio"),
    "🎙️": ("microfono", "podcast", "mic", "studio"),
    "🎚️": ("fader", "mezcla", "level", "slider"),
    "🎛️": ("mezclador", "audio", "knob", "mixing"),
    "⏰": ("alarma", "despertador", "alarm", "clock"),
    "🕰️": ("reloj", "antiguo", "mantel", "clock"),
    "⌛": ("reloj", "arena", "hourglass"),
    "⏳": ("reloj", "arena", "tiempo", "hourglass", "flowing"),
    "📡": ("antena", "satelite", "satellite", "antenna"),
    "🔋": ("bateria", "pila", "carga", "battery"),
    "🔌": ("enchufe", "cable", "plug", "electric"),
    "💡": ("bombilla", "idea", "luz", "bulb", "idea"),
    "🔦": ("linterna", "flashlight", "torch"),
    "🕯️": ("vela", "candle"),
    "💸": ("dinero", "alas", "gastar", "money", "wings"),
    "💵": ("dinero", "billete", "dollars", "cash"),
    "💴": ("yen", "dinero", "banknote"),
    "💶": ("euro", "dinero", "banknote"),
    "💷": ("libra", "dinero", "banknote"),
    "💰": ("dinero", "bolsa", "plata", "money", "bag"),
    "💳": ("tarjeta", "credito", "credit", "card"),
    "💎": ("diamante", "joya", "gem", "jewel"),
    "🧰": ("caja", "herramientas", "toolbox"),
    "🔧": ("llave", "herramienta", "wrench"),
    "🔨": ("martillo", "hammer"),
    "🛠️": ("herramientas", "tools"),
    "⚙️": ("engranaje", "ajustes", "configuracion", "gear"),
    "🔫": ("pistola", "agua", "pistol", "gun"),
    "💣": ("bomba", "bomb"),
    "🔪": ("cuchillo", "knife"),
    "🛡️": ("escudo", "proteccion", "shield"),
    "🔮": ("bola", "cristal", "magia", "crystal", "ball"),
    "🔭": ("telescopio", "telescope"),
    "🔬": ("microscopio", "microscope"),
    "🧪": ("tubo", "quimica", "laboratorio", "test", "tube"),
    "🩺": ("estetoscopio", "medico", "doctor", "stethoscope"),
    "🧹": ("escoba", "limpieza", "broom"),
    "🧺": ("cesta", "canasta", "basket"),
    "🧾": ("recibo", "ticket", "receipt"),
    "📃": ("documento", "rizado", "page", "curly"),
    "📄": ("documento", "hoja", "page", "facing"),
    "📋": ("clipboard", "bandeja", "clipboard"),
    "📊": ("grafico", "barras", "chart", "bar"),
    "📈": ("grafico", "subida", "chart", "increasing"),
    "📉": ("grafico", "bajada", "chart", "decreasing"),
    "📚": ("libros", "biblioteca", "books"),
    "📖": ("libro", "abierto", "book", "open"),
    "📗": ("libro", "verde", "book", "green"),
    "📘": ("libro", "azul", "book", "blue"),
    "📙": ("libro", "naranja", "book", "orange"),
    "📓": ("libreta", "notebook"),
    "📔": ("libreta", "cubierta", "notebook", "decorative"),
    "📒": ("libreta", "ledger"),
    "📕": ("libro", "rojo", "book", "closed"),
    "📰": ("periodico", "noticias", "newspaper"),
    "📑": ("marcadores", "bookmark", "tabs"),
    "🔖": ("marcapaginas", "bookmark"),
    "🏷️": ("etiqueta", "tag"),
    "🎁": ("regalo", "presente", "gift", "wrapped"),
    "🎀": ("lazo", "moño", "bow", "ribbon"),
    "🎊": ("confeti", "fiesta", "confetti", "ball"),
    "🎉": ("fiesta", "celebrar", "party", "popper"),
    "🎈": ("globo", "balloon"),
    "🎄": ("navidad", "arbol", "christmas", "tree"),
    "🎃": ("calabaza", "halloween", "jack", "lantern"),
    "🧧": ("sobre rojo", "dinero", "envelope", "lucky"),
    "🎎": ("munecas", "japonesas", "dolls"),
    "🎏": ("banderas", "koinobori", "carp", "streamer"),
    "🎐": ("campanilla", "viento", "wind", "chime"),
    "🧨": ("petardo", "fuegos", "firecracker"),
    "✨": ("estrellas", "brillo", "magia", "sparkles", "sparkle"),
    "🎆": ("fuegos", "artificiales", "fireworks"),
    "🎇": ("fuegos", "chispa", "fireworks", "sparkler"),
    "❤️": ("corazon", "rojo", "love", "red", "heart"),
    "🧡": ("corazon", "naranja", "naranja", "orange", "heart"),
    "💛": ("corazon", "amarillo", "yellow", "heart"),
    "💚": ("corazon", "verde", "green", "heart"),
    "💙": ("corazon", "azul", "blue", "heart"),
    "💜": ("corazon", "morado", "purple", "heart"),
    "🖤": ("corazon", "negro", "black", "heart"),
    "🤍": ("corazon", "blanco", "white", "heart"),
    "🤎": ("corazon", "marron", "brown", "heart"),
    "💔": ("corazon", "roto", "rompecorazones", "broken", "heart"),
    "❣️": ("corazon", "exclamacion", "heart", "exclamation"),
    "💕": ("corazones", "dos", "two", "hearts"),
    "💞": ("corazones", "revoloteo", "revolving", "hearts"),
    "💓": ("corazon", "latido", "beating", "heart"),
    "💗": ("corazon", "creciente", "growing", "heart"),
    "💖": ("corazon", "brillante", "sparkling", "heart"),
    "💘": ("corazon", "flecha", "cupido", "heart", "arrow"),
    "💝": ("corazon", "lazo", "caja", "heart", "ribbon"),
    "💟": ("corazon", "decoracion", "heart", "decoration"),
    "💋": ("beso", "labios", "kiss", "mark"),
    "💌": ("carta", "amor", "love", "letter"),
    "💬": ("burbuja", "chat", "mensaje", "speech", "bubble"),
    "💭": ("pensamiento", "nube", "thought", "balloon"),
    "🗯️": ("enojo", "burbuja", "anger", "bubble"),
    "💤": ("zzz", "sueno", "zzz", "sleep"),
    "✅": ("check", "listo", "correcto", "check", "mark"),
    "❌": ("equis", "error", "cruz", "cross", "error"),
    "❎": ("equis", "cuadrado", "cross", "button"),
    "⭕": ("circulo", "rojo", "o", "ring"),
    "🛑": ("alto", "stop", "pare", "stop", "sign"),
    "⛔": ("prohibido", "no", "no", "entry"),
    "📛": ("nombre", "placa", "name", "badge"),
    "🚫": ("prohibido", "no", "prohibited", "forbidden"),
    "💯": ("cien", "perfecto", "100", "hundred"),
    "💢": ("enojo", "enojado", "anger"),
    "♨️": ("onzen", "vapor", "baño", "hot", "springs"),
    "🚷": ("no peatones", "no", "pedestrians"),
    "🚯": ("no basura", "no", "litter"),
    "🚳": ("no bicicletas", "no", "bicycles"),
    "🚱": ("no agua", "no", "drinking"),
    "🔞": ("mayoria", "18", "no", "one", "eighteen"),
    "📵": ("no celular", "no", "mobile"),
    "🚭": ("no fumar", "no", "smoking"),
    "❗": ("exclamacion", "alerta", "exclamation"),
    "❕": ("exclamacion", "blanca", "exclamation", "white"),
    "❓": ("interrogacion", "pregunta", "question"),
    "❔": ("interrogacion", "blanca", "question", "white"),
    "‼️": ("exclamacion", "doble", "double", "exclamation"),
    "⁉️": ("interrogacion", "exclamacion", "question", "exclamation"),
    "🔅": ("bajo", "brillo", "low", "brightness"),
    "🔆": ("alto", "brillo", "high", "brightness"),
    "⚠️": ("advertencia", "alerta", "warning"),
    "🚸": ("niños", "escuela", "children", "crossing"),
    "🔱": ("tridente", "emblema", "trident"),
    "⚜️": ("lis", "flor", "fleur", "de", "lis"),
    "🔰": ("novato", "japones", "beginner"),
    "♻️": ("reciclar", "reciclaje", "recycle", "recycling"),
    "🈯": ("reservado", "japones", "reserved"),
    "💹": ("grafico", "yen", "chart", "increasing"),
    "❇️": ("chispa", "sparkle"),
    "✳️": ("asterisco", "ocho", "eight", "spoked"),
    "🌐": ("globo", "internet", "globe", "meridians"),
    "💠": ("diamante", "puntos", "diamond", "dot"),
    "Ⓜ️": ("metro", "m", "circle"),
    "🌀": ("simbolo", "tornado", "cyclone"),
    "🏧": ("atm", "cajero", "bank"),
    "🚾": ("wc", "baño", "banio", "restroom"),
    "♿": ("discapacidad", "accesible", "wheelchair"),
    "🅿️": ("parking", "estacionamiento", "parking"),
    "🈳": ("vacio", "japones", "vacancy"),
    "🈂️": ("servicio", "japones", "service"),
    "🛂": ("pasaporte", "control", "passport", "control"),
    "🛃": ("aduana", "customs"),
    "🛄": ("equipaje", "baggage", "claim"),
    "🛅": ("consigna", "equipaje", "left", "luggage"),
    "🚹": ("hombre", "banio", "wc", "man", "restroom"),
    "🚺": ("mujer", "banio", "wc", "woman", "restroom"),
    "🚼": ("bebe", "cambio", "baby", "symbol"),
    "⚧️": ("trans", "transgender", "symbol"),
    "🚻": ("banios", "wc", "restroom"),
    "🚮": ("basura", "tirar", "litter", "bin"),
    "🎦": ("cine", "camara", "film", "clapper"),
    "📶": ("wifi", "señal", "antenna", "bars"),
    "ℹ️": ("informacion", "info", "information"),
    "🔤": ("abc", "letras", "alphabet"),
    "🔡": ("abc", "minusculas", "lowercase"),
    "🔠": ("abc", "mayusculas", "uppercase"),
    "🆖": ("no", "ng", "ng", "button"),
    "🆗": ("ok", "boton", "ok", "button"),
    "🆙": ("subir", "arriba", "up", "button"),
    "🆒": ("genial", "cool", "button"),
    "🆕": ("nuevo", "new", "button"),
    "🆓": ("gratis", "free", "button"),
    "0️⃣": ("cero", "numero", "zero"),
    "1️⃣": ("uno", "numero", "one"),
    "2️⃣": ("dos", "numero", "two"),
    "3️⃣": ("tres", "numero", "three"),
    "4️⃣": ("cuatro", "numero", "four"),
    "5️⃣": ("cinco", "numero", "five"),
    "6️⃣": ("seis", "numero", "six"),
    "7️⃣": ("siete", "numero", "seven"),
    "8️⃣": ("ocho", "numero", "eight"),
    "9️⃣": ("nueve", "numero", "nine"),
    "🔟": ("diez", "numero", "keycap", "ten"),
    "🔢": ("numeros", "1234", "input", "numbers"),
    "#️⃣": ("numeral", "hash", "hash"),
    "*️⃣": ("asterisco", "star", "asterisk"),
    "▶️": ("reproducir", "play", "play"),
    "⏸️": ("pausa", "pause"),
    "⏯️": ("play", "pausa", "play", "pause"),
    "⏹️": ("detener", "stop"),
    "⏺️": ("grabar", "record"),
    "⏭️": ("siguiente", "next", "track"),
    "⏮️": ("anterior", "previous", "track"),
    "⏩": ("avanzar", "adelantar", "fast", "forward"),
    "⏪": ("retroceder", "rewind"),
    "⏫": ("subir", "rapido", "fast", "up"),
    "⏬": ("bajar", "rapido", "fast", "down"),
    "◀️": ("izquierda", "flecha", "leftwards"),
    "🔼": ("arriba", "triangulo", "up", "button"),
    "🔽": ("abajo", "triangulo", "down", "button"),
    "➡️": ("derecha", "flecha", "arrow", "right"),
    "⬅️": ("izquierda", "flecha", "arrow", "left"),
    "⬆️": ("arriba", "flecha", "arrow", "up"),
    "⬇️": ("abajo", "flecha", "arrow", "down"),
    "↗️": ("diagonal", "arriba", "northeast", "arrow"),
    "↘️": ("diagonal", "abajo", "southeast", "arrow"),
    "↙️": ("diagonal", "abajo", "southwest", "arrow"),
    "↖️": ("diagonal", "arriba", "northwest", "arrow"),
    "↕️": ("arriba", "abajo", "up", "down", "arrow"),
    "↔️": ("izquierda", "derecha", "left", "right", "arrow"),
    "↪️": ("entrar", "rotate", "arrow"),
    "↩️": ("volver", "repsonder", "rotate", "arrow"),
    "⤴️": ("girar", "arriba", "upper", "arrow"),
    "⤵️": ("girar", "bajar", "lower", "arrow"),
    "🔀": ("mezclar", "shuffle", "tracks"),
    "🔁": ("repetir", "repeat", "tracks"),
    "🔂": ("repetir", "uno", "repeat", "single"),
    "🔄": ("sudoeste", "refrescar", "anticlockwise", "arrows"),
    "🔃": ("recargar", "clockwise", "vertical"),
    "🎵": ("nota", "musica", "musical", "note"),
    "🎶": ("notas", "musica", "musical", "notes"),
    "➕": ("mas", "sumar", "plus"),
    "➖": ("menos", "restar", "minus"),
    "➗": ("dividir", "division", "divide"),
    "✖️": ("multiplicar", "equis", "multiply"),
    "♾️": ("infinito", "infinite"),
    "💲": ("dolar", "signo", "heavy", "dollar"),
    "💱": ("cambio", "moneda", "currency", "exchange"),
    "™️": ("marca", "registrada", "trade", "mark"),
    "©️": ("copyright", "derechos", "copyright"),
    "®️": ("registrada", "marca", "registered"),
    "〰️": ("ondulado", "tilde", "wavy", "dash"),
    "➰": ("lazo", "curled", "loop"),
    "➿": ("doble", "lazo", "double", "curly"),
    "🔚": ("fin", "end", "arrow"),
    "🔙": ("volver", "back", "arrow"),
    "🔛": ("on", "activado", "on", "arrow"),
    "🔝": ("top", "arriba", "top", "arrow"),
    "🔜": ("pronto", "soon", "arrow"),
    "✔️": ("check", "correcto", "heavy", "check"),
    "☑️": ("check", "casilla", "ballot", "box"),
    "🔘": ("radio", "boton", "radio", "button"),
    "🔴": ("circulo", "rojo", "red", "circle"),
    "🟠": ("circulo", "naranja", "orange", "circle"),
    "🟡": ("circulo", "amarillo", "yellow", "circle"),
    "🟢": ("circulo", "verde", "green", "circle"),
    "🔵": ("circulo", "azul", "blue", "circle"),
    "🟣": ("circulo", "morado", "purple", "circle"),
    "⚫": ("circulo", "negro", "black", "circle"),
    "⚪": ("circulo", "blanco", "white", "circle"),
    "🟤": ("circulo", "marron", "brown", "circle"),
    "🔺": ("triangulo", "rojo", "red", "triangle"),
    "🔻": ("triangulo", "abajo", "small", "down"),
    "🔸": ("diamante", "naranja", "small", "orange"),
    "🔹": ("diamante", "azul", "small", "blue"),
    "🔶": ("diamante", "naranja", "large", "orange"),
    "🔷": ("diamante", "azul", "large", "blue"),
    "🔳": ("cuadrado", "blanco", "white", "square"),
    "🔲": ("cuadrado", "negro", "black", "square"),
    "▪️": ("cuadrado", "negro", "black", "small"),
    "▫️": ("cuadrado", "blanco", "white", "small"),
    "◾": ("cuadrado", "negro", "black", "medium"),
    "◽": ("cuadrado", "blanco", "white", "medium"),
    "◼️": ("cuadrado", "negro", "black", "medium"),
    "◻️": ("cuadrado", "blanco", "white", "medium"),
    "🟥": ("cuadrado", "rojo", "red", "square"),
    "🟧": ("cuadrado", "naranja", "orange", "square"),
    "🟨": ("cuadrado", "amarillo", "yellow", "square"),
    "🟩": ("cuadrado", "verde", "green", "square"),
    "🟦": ("cuadrado", "azul", "blue", "square"),
    "🟪": ("cuadrado", "morado", "purple", "square"),
    "⬛": ("cuadrado", "negro", "black", "large"),
    "⬜": ("cuadrado", "blanco", "white", "large"),
    "🟫": ("cuadrado", "marron", "brown", "square"),
    "🔈": ("volumen", "bajo", "speaker", "low"),
    "🔇": ("mudo", "sin sonido", "muted", "speaker"),
    "🔉": ("volumen", "medio", "speaker", "medium"),
    "🔊": ("volumen", "alto", "speaker", "high"),
    "🔔": ("campana", "notificacion", "bell"),
    "🔕": ("campana", "mudo", "bell", "slashed"),
    "📣": ("megafono", "anuncio", "megaphone"),
    "📢": ("altavoz", "anuncio", "loudspeaker"),
    "♠️": ("picas", "spade", "suit"),
    "♣️": ("trebol", "club", "suit"),
    "♥️": ("corazon", "picas", "heart", "suit"),
    "♦️": ("diamante", "diamond", "suit"),
    "🃏": ("comodin", "joker", "card"),
    "🎴": ("cartas", "japonesas", "flower", "cards"),
    "🀄": ("mahjong", "dragón", "mahjong", "red"),
    "⭐": ("estrella", "star"),
    "🌟": ("estrella", "brillante", "glowing", "star"),
    "💫": ("estrella", "girar", "dizzy", "star"),
    "🔥": ("fuego", "caliente", "trending", "fire"),
    "💥": ("explosion", "colision", "collision"),
    "🎯": ("objetivo", "diana", "target"),
    "🚀": ("cohete", "lanzamiento", "despegar", "rocket", "launch"),
    "👑": ("corona", "rey", "reina", "crown"),
    "🥇": ("oro", "primero", "gold", "medal"),
    "🎭": ("teatro", "mascaras", "performing", "arts"),
    "🎪": ("circo", "carpa", "circus", "tent"),
    "🎨": ("arte", "paleta", "art", "palette"),
    "🎤": ("microfono", "micrófono", "karaoke", "microphone"),
    "🎸": ("guitarra", "guitar"),
    "🎹": ("teclado", "musical", "musical", "keyboard"),
    "🥁": ("tambor", "bateria", "drum"),
    "🎺": ("trompeta", "trumpet"),
    "🎻": ("violin", "violin"),
    "💃": ("bailar", "mujer", "dancing", "dancer"),
    "🕺": ("bailar", "hombre", "dancing", "dancer"),
    "⚡": ("rayo", "electricidad", "peligro", "zap", "lightning"),
    "🌪️": ("tornado", "tornado"),
    "🌈": ("arcoiris", "arco", "rainbow"),
    "🦄": ("unicornio", "unicorn"),
    "🍾": ("champagne", "brindis", "celebracion"),
    "🥂": ("copas", "brindis", "toast"),
    "🍻": ("cerveza", "brindis", "beers"),
    "🍺": ("cerveza", "beer"),
    "🎂": ("pastel", "cumpleaños", "birthday", "cake"),
    "🧁": ("cupcake", "magdalena", "cupcake"),
    "🍰": ("torta", "pastel", "shortcake"),
    "🎈": ("globo", "balloon"),
    "🎁": ("regalo", "gift", "present"),
    "🎉": ("fiesta", "celebrar", "party", "tada"),
    "🎊": ("confeti", "fiesta", "confetti"),
    "😍": ("amor", "ojos", "corazones", "smiling"),
    "🤩": ("estrella", "maravillado", "star", "struck"),
    "😎": ("lentes", "genial", "sunglasses", "cool"),
    "🤗": ("abrazo", "feliz", "hug", "smiling"),
    "😂": ("risa", "llorar", "joy"),
    "🤣": ("risa", "carcajada", "rofl"),
    "🤯": ("explosion", "cabeza", "mind"),
    "😭": ("llorar", "lagrimas", "crying"),
    "🥳": ("fiesta", "celebrar", "party"),
    "🤔": ("pensar", "reflexion", "thinking"),
    "💖": ("corazon", "brillo", "sparkling", "heart"),
    "💘": ("flecha", "corazon", "cupido", "heart", "arrow"),
    "💝": ("corazon", "lazo", "regalo", "heart", "ribbon"),
    "💋": ("beso", "labios", "kiss"),
    "🥰": ("enamorado", "corazones", "love"),
    "😘": ("beso", "soplar", "kissing"),
    "🤤": ("baba", "delicioso", "drooling"),
    "🥹": ("lucha", "lagrimas", "contenido", "hold", "tears"),
    "🙂": ("sonrisa", "timida", "slight"),
    "🥲": ("sonrisa", "lagrima", "smiling", "tear"),
    "🦁": ("leon", "lion"),
    "🐯": ("tigre", "tiger"),
    "🐼": ("panda", "panda"),
    "🐨": ("koala", "koala"),
    "🦊": ("zorro", "fox"),
    "🐻": ("oso", "bear"),
    "🦝": ("mapache", "raccoon"),
    "🐺": ("lobo", "wolf"),
    "🦓": ("cebra", "zebra"),
    "🦌": ("ciervo", "deer"),
    "🐘": ("elefante", "elephant"),
    "🦏": ("rinoceronte", "rhinoceros"),
    "🐪": ("camello", "camel"),
    "🐫": ("camello", "doble", "camel", "two"),
    "🦒": ("jirafa", "giraffe"),
    "🐃": ("bufalo", "agua", "buffalo"),
    "🐂": ("toro", "ox"),
    "🐄": ("vaca", "cow"),
    "🐎": ("caballo", "galopar", "horse", "racing"),
    "🐖": ("cerdo", "pig"),
    "🐏": ("carnero", "ram"),
    "🐑": ("oveja", "sheep", "ewe"),
    "🐐": ("cabra", "goat"),
    "🐓": ("gallo", "rooster"),
    "🦃": ("pavo", "turkey"),
    "🦚": ("pavo real", "peacock"),
    "🦜": ("loro", "parrot"),
    "🦢": ("cisne", "swan"),
    "🦩": ("flamenco", "flamingo"),
    "🦔": ("erizo", "hedgehog"),
    "🐿️": ("ardilla", "squirrel"),
    "🦫": ("castor", "beaver"),
    "🦥": ("perezoso", "sloth"),
    "🦦": ("nutria", "otter"),
    "🦨": ("zorrillo", "mofeta", "skunk"),
    "🦘": ("canguro", "kangaroo"),
    "🦡": ("tejon", "badger"),
    "🐇": ("conejo", "liebre", "rabbit"),
    "🐁": ("raton", "mouse"),
    "🐀": ("rata", "rat"),
    "🐿️": ("ardilla", "chipmunk"),
    "🐅": ("tigre", "tiger"),
    "🐆": ("leopardo", "leopard"),
    "🐈": ("gato", "cat"),
    "🐕": ("perro", "dog"),
    "🦮": ("perro", "guia", "guide", "dog"),
    "🐩": ("perro", "poodle"),
    "🐕‍🦺": ("perro", "asistencia", "service", "dog"),
    "🐈‍⬛": ("gato", "negro", "black", "cat"),
}

# Emojis "Premium" (candidatos a recientes por ser usados con frecuencia).
PREMADE_TAGS = ("🔥", "✨", "🎯", "🚀", "⭐", "💎", "💰", "🔥", "🎉")


# --- Emojis organizados por categoría (fuente del picker) ---

EMOJIS = {
    "Caritas": [
        "😀","😃","😄","😁","😆","😅","🤣","😂","🙂","🙃","😉","😊","😇","🥰","😍","🤩","😘","😗",
        "☺️","😚","😙","🥲","😋","😛","😜","🤪","😝","🤑","🤗","🤭","🤫","🤔","🤐","🤨","😐","😑",
        "😶","😶‍🌫️","😏","😒","🙄","😬","😮‍💨","🤥","😔","😪","🤤","😴","😷","🤒","🤕","🤢","🤮",
        "🤧","🥵","🥶","🥴","😵","😵‍💫","🤯","🤠","🥳","🥸","😎","🤓","🧐","😕","😟","🙁","☹️","😮",
        "😯","😲","😳","🥺","😦","😧","😨","😰","😥","😢","😭","😱","😖","😣","😞","😓","😩","😫",
        "🥱","😤","😡","😠","🤬","😈","👿","💀","☠️","💩","🤡","👻","👽","🤖"
    ],
    "Gestos": [
        "👋","🤚","🖐️","✋","🖖","👌","🤌","🤏","✌️","🤞","🤟","🤘","🤙","👈","👉","👆","🖕","👇",
        "☝️","👍","👎","👊","✊","🤛","🤜","👏","🙌","👐","🤲","🤝","🙏","✍️","💅","🤳","💪"
    ],
    "Animales": [
        "🐶","🐱","🐭","🐹","🐰","🦊","🐻","🐼","🐨","🐯","🦁","🐮","🐷","🐸","🐵","🙈","🙉","🙊",
        "🐔","🐧","🐦","🐤","🐣","🐥","🦆","🦅","🦉","🦇","🐺","🐗","🐴","🦄","🐝","🦋","🐌","🐞",
        "🐢","🐍","🦖","🦕","🐬","🐳","🐋","🐊"
    ],
    "Comida": [
        "🍎","🍐","🍊","🍋","🍌","🍉","🍇","🍓","🍒","🍑","🥭","🍍","🥥","🥝","🍅","🍆",
        "🥑","🥦","🥬","🥒","🌶️","🌽","🥕","🥔","🍠","🥐","🥖","🍞","🥨","🥯","🥞","🧇",
        "🥓","🥩","🍗","🍖","🌭","🍔","🍟","🍕","🥪","🥙","🌮","🌯","🥗","🥘","🍝","🍜",
        "🍲","🍛","🍣","🍱","🥟","🍤","🍙","🍚","🍘","🍥","🥠","🍢","🍡","🍧","🍨","🍦",
        "🥧","🧁","🍰","🎂","🍮","🍭","🍬","🍫","🍿","🍩","🍪","☕","🍵","🧃","🥤","🧋",
        "🍺","🍻","🥂","🍷","🥃","🍸","🍹","🍾","🧊"
    ],
    "Deportes": [
        "⚽","🏀","🏈","⚾","🥎","🎾","🏐","🏉","🎱","🏓","🏸","🏑","🏒","🥍","🏏","🥅","⛳","🏹",
        "🎣","🥊","🥋","🎽","🛹","🛼","⛸️","🥌","🎿","⛷️","🏂","🏋️","🤼","🤸","⛹️","🤺","🤾",
        "🏌️","🧘","🏄","🏊","🤽","🚣","🧗","🚵","🚴","🏆","🥇","🥈","🥉","🏅","🎖️"
    ],
    "Objetos": [
        "⌚","📱","💻","⌨️","🖥️","🖨️","🖱️","🕹️","💽","💾","💿","📷","📸","📹","🎥","📞","☎️",
        "📺","📻","🎙️","🎚️","🎛️","⏰","🕰️","⌛","⏳","📡","🔋","🔌","💡","🔦","🕯️","💸","💵",
        "💴","💶","💷","💰","💳","💎","🧰","🔧","🔨","🛠️","⛏️","🔩","⚙️","🔫","💣","🔪","🗡️",
        "🛡️","🚬","⚰️","🏺","🔮","📿","💈","🔭","🔬","🧬","🧫","🧪","🌡️","🧹","🧺","🧾","📃",
        "📄","📋","📊","📈","📉","📚","📖","📗","📘","📙","📓","📔","📒","📕","📰","📑","🔖",
        "🏷️","🎁","🎀","🎊","🎉","🎈","🎄","🎃","🧧","🎎","🎏","🎐","🧨","✨","🎆","🎇","🩺"
    ],
    "Simbolos": [
        "❤️","🧡","💛","💚","💙","💜","🖤","🤍","🤎","💔","❣️","💕","💞","💓","💗","💖","💘",
        "💝","💟","☮️","✝️","☪️","🕉️","☸️","✡️","🔯","🕎","☯️","☦️","🛐","♈","♉","♊",
        "♋","♌","♍","♎","♏","♐","♑","♒","♓","🆔","⚛️","☢️","☣️","📴","📳","🈶","🈚",
        "🈸","🈺","🈷️","✴️","🆚","💮","🉐","㊙️","㊗️","🈴","🈵","🈹","🈲","🅰️","🅱️","🆎",
        "🆑","🅾️","🆘","❌","⭕","🛑","⛔","📛","🚫","💯","💢","♨️","🚷","🚯","🚳","🚱","🔞",
        "📵","🚭","❗","❕","❓","❔","‼️","⁉️","🔅","🔆","⚠️","🚸","🔱","⚜️","🔰","♻️",
        "✅","🈯","💹","❇️","✳️","❎","🌐","💠","Ⓜ️","🌀","💤","🏧","🚾","♿","🅿️","🈳","🈂️",
        "🛂","🛃","🛄","🛅","🚹","🚺","🚼","⚧️","🚻","🚮","🎦","📶","🈁","🔣","ℹ️","🔤","🔡",
        "🔠","🆖","🆗","🆙","🆒","🆕","🆓","0️⃣","1️⃣","2️⃣","3️⃣","4️⃣","5️⃣","6️⃣","7️⃣","8️⃣",
        "9️⃣","🔟","🔢","#️⃣","*️⃣","⏏️","▶️","⏸️","⏯️","⏹️","⏺️","⏭️","⏮️","⏩","⏪","⏫",
        "⏬","◀️","🔼","🔽","➡️","⬅️","⬆️","⬇️","↗️","↘️","↙️","↖️","↕️","↔️","↪️","↩️",
        "⤴️","⤵️","🔀","🔁","🔂","🔄","🔃","🎵","🎶","➕","➖","➗","✖️","♾️","💲","💱",
        "™️","©️","®️","〰️","➰","➿","🔚","🔙","🔛","🔝","🔜","✔️","☑️","🔘","🔴","🟠",
        "🟡","🟢","🔵","🟣","⚫","⚪","🟤","🔺","🔻","🔸","🔹","🔶","🔷","🔳","🔲","▪️",
        "▫️","◾","◽","◼️","◻️","🟥","🟧","🟨","🟩","🟦","🟪","⬛","⬜","🟫","🔈","🔇",
        "🔉","🔊","🔔","🔕","📣","📢","💬","💭","🗯️","♠️","♣️","♥️","♦️","🃏","🎴",
        "🀄"
    ],
}


def emoji_name(emoji: str) -> str:
    """Nombre legible para tooltip: primer tag ES si existe."""
    tags = EMOJI_INDEX.get(emoji)
    if tags:
        return " ".join(tags[:3]).capitalize()
    return emoji


def search_emojis(query: str, emojis: list[str] | None = None) -> list[str]:
    """Devuelve emojis que coinciden con la búsqueda.

    * Busca en los tags (es/en, sin acentos).
    * Como fallback, coincide por subcadena de caracteres (ej. `\U0001F600`).
    """
    q = normalize(query.strip())
    if not q:
        return list(emojis) if emojis is not None else []

    pool = emojis if emojis is not None else list(EMOJI_INDEX.keys())
    hits: list[tuple[int, str]] = []
    for emoji in pool:
        tags = EMOJI_INDEX.get(emoji)
        if tags is None:
            # Fallback manual: match por caracteres del propio emoji
            if q and any(q in normalize(t) for t in (emoji,)):
                hits.append((2, emoji))
            continue
        for i, tag in enumerate(tags[:3]):
            if tag.startswith(q):
                hits.append((0 + i * 0.5, emoji))
                break
            if q in tag:
                hits.append((1, emoji))
                break
    hits.sort(key=lambda t: (t[0], len(EMOJI_INDEX.get(t[1], ()))))
    seen = set()
    out = []
    for _, emoji in hits:
        if emoji not in seen:
            seen.add(emoji)
            out.append(emoji)
    return out


# --- Recientes ---

def load_recent() -> list[str]:
    try:
        if not _RECENT_FILE.exists():
            return []
        import json
        with open(_RECENT_FILE, "r", encoding="utf-8") as f:
            data = json.load(f)
        return [e for e in data if isinstance(e, str)][: _RECENT_MAX]
    except Exception:
        return []


def add_recent(emoji: str) -> None:
    """Marca `emoji` como usado recientemente (persistente)."""
    try:
        _RECENT_FILE.parent.mkdir(parents=True, exist_ok=True)
        recents = load_recent()
        recents = [e for e in recents if e != emoji]
        recents.insert(0, emoji)
        recents = recents[: _RECENT_MAX]
        import json
        with open(_RECENT_FILE, "w", encoding="utf-8") as f:
            json.dump(recents, f, ensure_ascii=False)
    except Exception:
        pass